import { describe, it, expect } from 'vitest';
import { getAdapter, ADAPTER_IDS } from '../src/adapters/agents/index.js';
import type { SkillSource } from '../src/adapters/agents/types.js';

const SKILL: SkillSource = {
  id: 'plan',
  title: 'Plan a SpiralSpec spec',
  description: 'Generate the task breakdown.',
  args: '<spec-slug>',
  body: '# SpiralSpec — Plan\n\nDo the thing.',
};

describe('adapters', () => {
  it('exposes claude and opencode', () => {
    expect(ADAPTER_IDS).toEqual(['claude', 'opencode']);
    expect(() => getAdapter('cursor')).toThrow('unknown agent: cursor');
  });

  it('claude renders a skill and a command per source', () => {
    const files = getAdapter('claude').render([SKILL], '0.1.0');
    expect(files.map((f) => f.relPath)).toEqual([
      '.claude/skills/spiralspec-plan/SKILL.md',
      '.claude/commands/spiral/plan.md',
    ]);
    const skill = files[0].content;
    expect(skill).toContain('name: spiralspec-plan');
    expect(skill).toContain('description: Generate the task breakdown.');
    expect(skill).toContain('generated by spiralspec v0.1.0');
    expect(skill).toContain('# SpiralSpec — Plan');
    expect(skill.indexOf('---')).toBe(0);
    const command = files[1].content;
    expect(command).toContain('$ARGUMENTS');
    expect(command).toContain('spiralspec-plan');
  });

  it('opencode renders one flat command per source with the full body', () => {
    const files = getAdapter('opencode').render([SKILL], '0.1.0');
    expect(files.map((f) => f.relPath)).toEqual(['.opencode/commands/spiral-plan.md']);
    expect(files[0].content).toContain('Target: $ARGUMENTS');
    expect(files[0].content).toContain('Do the thing.');
    expect(files[0].content).toContain('generated by spiralspec v0.1.0');
  });
});
