import { describe, it, expect } from 'vitest';
import yaml from 'js-yaml';
import matter from 'gray-matter';
import { getAdapter, ADAPTER_IDS } from '../src/adapters/agents/index.js';
import type { SkillSource } from '../src/adapters/agents/types.js';

const SKILL: SkillSource = {
  id: 'plan',
  title: 'Plan a SpiralSpec spec',
  description: 'Generate the task breakdown.',
  args: '<spec-slug>',
  body: '# SpiralSpec — Plan\n\nDo the thing.',
};

const HOSTILE_DESCRIPTION = 'Summary: does "A: B" and #things\nacross multiple\nlines';
const HOSTILE_SKILL: SkillSource = { ...SKILL, id: 'hostile', description: HOSTILE_DESCRIPTION };

describe('adapters', () => {
  it('exposes claude and opencode', () => {
    expect(ADAPTER_IDS).toEqual(['claude', 'opencode']);
    expect(() => getAdapter('cursor')).toThrow('unknown agent: cursor');
  });

  it('claude renders a skill and a command per source', () => {
    const files = getAdapter('claude').render([SKILL], '0.1.0');
    expect(files.map((f) => f.relPath)).toEqual([
      '.claude/skills/spiralspec-plan/SKILL.md',
      '.claude/commands/spiral/plan.md',
    ]);
    const skill = files[0].content;
    expect(skill).toContain('name: spiralspec-plan');
    expect(skill).toContain('description: Generate the task breakdown.');
    expect(skill).toContain('generated by spiralspec v0.1.0');
    expect(skill).toContain('# SpiralSpec — Plan');
    expect(skill.indexOf('---')).toBe(0);
    const command = files[1].content;
    expect(command).toContain('$ARGUMENTS');
    expect(command).toContain('spiralspec-plan');
  });

  it('opencode renders one flat command per source with the full body', () => {
    const files = getAdapter('opencode').render([SKILL], '0.1.0');
    expect(files.map((f) => f.relPath)).toEqual(['.opencode/commands/spiral-plan.md']);
    expect(files[0].content).toContain('Target: $ARGUMENTS');
    expect(files[0].content).toContain('Do the thing.');
    expect(files[0].content).toContain('generated by spiralspec v0.1.0');
  });

  it('claude escapes a hostile description (colon, hash, newlines) into valid, round-tripping YAML', () => {
    const files = getAdapter('claude').render([HOSTILE_SKILL], '0.1.0');
    const skill = files[0].content;
    const command = files[1].content;
    const skillFm = matter(skill).data;
    const commandFm = matter(command).data;
    expect(skillFm.name).toBe('spiralspec-hostile');
    expect(skillFm.description).toBe(HOSTILE_DESCRIPTION);
    expect(commandFm.description).toBe(HOSTILE_DESCRIPTION);
  });

  it('opencode escapes a hostile description into valid, round-tripping YAML', () => {
    const files = getAdapter('opencode').render([HOSTILE_SKILL], '0.1.0');
    const fm = matter(files[0].content).data;
    expect(fm.description).toBe(HOSTILE_DESCRIPTION);
  });

  it('yaml.load directly parses the frontmatter block for both adapters', () => {
    for (const adapter of ['claude', 'opencode'] as const) {
      const files = getAdapter(adapter).render([HOSTILE_SKILL], '0.1.0');
      for (const file of files) {
        const fmBlock = file.content.split('---\n')[1];
        const data = yaml.load(fmBlock) as Record<string, unknown>;
        expect(data.description).toBe(HOSTILE_DESCRIPTION);
      }
    }
  });
});
