export interface SkillSource {
  id: string;
  title: string;
  description: string;
  args: string;
  body: string;
}

export interface RenderedFile {
  relPath: string;
  content: string;
}

export interface AgentAdapter {
  id: string;
  render(skills: SkillSource[], version: string): RenderedFile[];
}

export function marker(version: string): string {
  return `<!-- generated by spiralspec v${version} — do not edit; see docs to customize -->`;
}
